; PlatformIO Project Configuration File
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:v1]
platform = atmelavr
board_build.mcu   = at90s1200
build_flags       = -D OLD_MCU=1
extra_scripts     = linkflags.py

[env:v2]
platform = atmelavr
board_build.mcu   = atmega48pa
build_flags       = -D OLD_KEY=1
extra_scripts     = linkflags.py

[env:v3]
platform = atmelavr
board_build.mcu   = atmega48pa
build_flags       = -D NEW_KEY=1
extra_scripts     = linkflags.py
