; PlatformIO Project Configuration File
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:v2]
platform = atmelavr
board_build.mcu   = atmega48pa
build_flags       = -D OLD_KEY=1,-nostartfiles,-nodefaultlibs,-Wl,--entry=0x0,--section-start=.text=0x0,--undefined=main

[env:v3]
platform = atmelavr
board_build.mcu   = atmega48pa
build_flags       = -D NEW_KEY=1,-nostartfiles,-nodefaultlibs,-Wl,--entry=0x0,--section-start=.text=0x0,--undefined=main
